d /run/t1bridge 0750 root t1bridge -
d /var/lib/t1bridge 0700 root root -
d /var/lib/t1bridge/machine-data 0700 root root -
d /var/lib/t1bridge/touch-id 0700 root root -
d /var/lib/t1bridge/touch-id/catacombs 0700 root root -
d /var/lib/t1bridge/touch-id/xart 0700 root root -
f /run/lock/t1-touchid-sep.lock 0600 root root -
